CREATE TABLE debug_environment (
    id VARCHAR(100) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    channel_id VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    target_ip VARCHAR(255),
    target_port INT,
    tmk_plain VARCHAR(64),
    tpk_plain VARCHAR(64),
    tsk_plain VARCHAR(64),
    mac_field VARCHAR(10),
    mac_algorithm VARCHAR(64) NOT NULL DEFAULT 'ANSI_X9_19',
    pin_algorithm VARCHAR(64) NOT NULL DEFAULT 'NONE',
    test_tid VARCHAR(64),
    test_sn VARCHAR(128),
    test_pan VARCHAR(64),
    test_de14 VARCHAR(16),
    test_de52 VARCHAR(256),
    test_de42 VARCHAR(64),
    test_de18 VARCHAR(16),
    test_de43 VARCHAR(128),
    test_de49 VARCHAR(16),
    variables_json JSON,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_debug_environment_user_channel (user_id, channel_id),
    CONSTRAINT fk_debug_environment_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);
